FROM nginx:alpine
COPY . /usr/share/nginx/html

# Installing and launching nginx web server without pulling actual ngix image
# docker build -t html-server-image:v1 .
# docker run -d -p 80:80 html-server-image:v1