#!/bin/sh
echo "docker-machine create --driver virtualbox Char"
eval $(docker-machine env Char)
docker volume create --name hatchery
docker run -d --name spawning-pool --restart=on-failure:10 -e MYSQL_ROOT_PASSWORD=Kerrigan -e MYSQL_DATABASE=zerglings -v hatchery:/var/lib/mysql mysql:5.7