FROM ubuntu
RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y default-jdk default-jre git vim
CMD bin/bash

# Inside of folder 'docker build -t java .'
# 'docker run --rm -ti java'
